// WARNING: This file has automatically been generated
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package internal

/*
#include "mpv.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

const (
	// _CLIENT_API_VERSION as defined in mpv/client.h:238
	_CLIENT_API_VERSION = 65645
	// _ENABLE_DEPRECATED as defined in mpv/client.h:247
	_ENABLE_DEPRECATED = 1
)

// error as declared in mpv/client.h:367
type error int32

// error enumeration from mpv/client.h:367
const (
	_ERROR_SUCCESS              = iota
	_ERROR_EVENT_QUEUE_FULL     = -1
	_ERROR_NOMEM                = -2
	_ERROR_UNINITIALIZED        = -3
	_ERROR_INVALID_PARAMETER    = -4
	_ERROR_OPTION_NOT_FOUND     = -5
	_ERROR_OPTION_FORMAT        = -6
	_ERROR_OPTION_ERROR         = -7
	_ERROR_PROPERTY_NOT_FOUND   = -8
	_ERROR_PROPERTY_FORMAT      = -9
	_ERROR_PROPERTY_UNAVAILABLE = -10
	_ERROR_PROPERTY_ERROR       = -11
	_ERROR_COMMAND              = -12
	_ERROR_LOADING_FAILED       = -13
	_ERROR_AO_INIT_FAILED       = -14
	_ERROR_VO_INIT_FAILED       = -15
	_ERROR_NOTHING_TO_PLAY      = -16
	_ERROR_UNKNOWN_FORMAT       = -17
	_ERROR_UNSUPPORTED          = -18
	_ERROR_NOT_IMPLEMENTED      = -19
	_ERROR_GENERIC              = -20
)

// format as declared in mpv/client.h:793
type format int32

// format enumeration from mpv/client.h:793
const (
	_FORMAT_NONE       = iota
	_FORMAT_STRING     = 1
	_FORMAT_OSD_STRING = 2
	_FORMAT_FLAG       = 3
	_FORMAT_INT64      = 4
	_FORMAT_DOUBLE     = 5
	_FORMAT_NODE       = 6
	_FORMAT_NODE_ARRAY = 7
	_FORMAT_NODE_MAP   = 8
	_FORMAT_BYTE_ARRAY = 9
)

// event_id as declared in mpv/client.h:1496
type event_id int32

// event_id enumeration from mpv/client.h:1496
const (
	_EVENT_NONE                  = iota
	_EVENT_SHUTDOWN              = 1
	_EVENT_LOG_MESSAGE           = 2
	_EVENT_GET_PROPERTY_REPLY    = 3
	_EVENT_SET_PROPERTY_REPLY    = 4
	_EVENT_COMMAND_REPLY         = 5
	_EVENT_START_FILE            = 6
	_EVENT_END_FILE              = 7
	_EVENT_FILE_LOADED           = 8
	_EVENT_TRACKS_CHANGED        = 9
	_EVENT_TRACK_SWITCHED        = 10
	_EVENT_IDLE                  = 11
	_EVENT_PAUSE                 = 12
	_EVENT_UNPAUSE               = 13
	_EVENT_TICK                  = 14
	_EVENT_SCRIPT_INPUT_DISPATCH = 15
	_EVENT_CLIENT_MESSAGE        = 16
	_EVENT_VIDEO_RECONFIG        = 17
	_EVENT_AUDIO_RECONFIG        = 18
	_EVENT_METADATA_UPDATE       = 19
	_EVENT_SEEK                  = 20
	_EVENT_PLAYBACK_RESTART      = 21
	_EVENT_PROPERTY_CHANGE       = 22
	_EVENT_CHAPTER_CHANGE        = 23
	_EVENT_QUEUE_OVERFLOW        = 24
	_EVENT_HOOK                  = 25
)

// log_level as declared in mpv/client.h:1556
type log_level int32

// log_level enumeration from mpv/client.h:1556
const (
	_LOG_LEVEL_NONE  = iota
	_LOG_LEVEL_FATAL = 10
	_LOG_LEVEL_ERROR = 20
	_LOG_LEVEL_WARN  = 30
	_LOG_LEVEL_INFO  = 40
	_LOG_LEVEL_V     = 50
	_LOG_LEVEL_DEBUG = 60
	_LOG_LEVEL_TRACE = 70
)

// end_file_reason as declared in mpv/client.h:1618
type end_file_reason int32

// end_file_reason enumeration from mpv/client.h:1618
const (
	_END_FILE_REASON_EOF      = iota
	_END_FILE_REASON_STOP     = 2
	_END_FILE_REASON_QUIT     = 3
	_END_FILE_REASON_ERROR    = 4
	_END_FILE_REASON_REDIRECT = 5
)

// sub_api as declared in mpv/client.h:2051
type sub_api int32

// sub_api enumeration from mpv/client.h:2051
const (
	_SUB_API_OPENGL_CB = 1
)
