// WARNING: This file has automatically been generated
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package internal

/*
#include "client.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import (
	"fmt"
	"runtime"
	"sync"
	"unsafe"
)

// Ref returns a reference to C object as it is.
func (x *mpv_handle) Ref() *C.mpv_handle {
	if x == nil {
		return nil
	}
	return (*C.mpv_handle)(unsafe.Pointer(x))
}

// Free cleanups the referenced memory using C free.
func (x *mpv_handle) Free() {
	if x != nil {
		C.free(unsafe.Pointer(x))
	}
}

// Newmpv_handleRef converts the C object reference into a raw struct reference without wrapping.
func mpv_handle_ref(ref unsafe.Pointer) *mpv_handle {
	return (*mpv_handle)(ref)
}

// Newmpv_handle allocates a new C object of this type and converts the reference into
// a raw struct reference without wrapping.
func mpv_handle_new() *mpv_handle {
	return (*mpv_handle)(allocMpv_handleMemory(1))
}

// allocMpv_handleMemory allocates memory for type C.mpv_handle in C.
// The caller is responsible for freeing the this memory via C.free.
func allocMpv_handleMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfMpv_handleValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfMpv_handleValue = unsafe.Sizeof([1]C.mpv_handle{})

// cgoAllocMap stores pointers to C allocated memory for future reference.
type cgoAllocMap struct {
	mux sync.RWMutex
	m   map[unsafe.Pointer]struct{}
}

var cgoAllocsUnknown = new(cgoAllocMap)

func (a *cgoAllocMap) Add(ptr unsafe.Pointer) {
	a.mux.Lock()
	if a.m == nil {
		a.m = make(map[unsafe.Pointer]struct{})
	}
	a.m[ptr] = struct{}{}
	a.mux.Unlock()
}

func (a *cgoAllocMap) IsEmpty() bool {
	a.mux.RLock()
	isEmpty := len(a.m) == 0
	a.mux.RUnlock()
	return isEmpty
}

func (a *cgoAllocMap) Borrow(b *cgoAllocMap) {
	if b == nil || b.IsEmpty() {
		return
	}
	b.mux.Lock()
	a.mux.Lock()
	for ptr := range b.m {
		if a.m == nil {
			a.m = make(map[unsafe.Pointer]struct{})
		}
		a.m[ptr] = struct{}{}
		delete(b.m, ptr)
	}
	a.mux.Unlock()
	b.mux.Unlock()
}

func (a *cgoAllocMap) Free() {
	a.mux.Lock()
	for ptr := range a.m {
		C.free(ptr)
		delete(a.m, ptr)
	}
	a.mux.Unlock()
}

// PassRef returns a reference to C object as it is or allocates a new C object of this type.
func (x *mpv_handle) PassRef() *C.mpv_handle {
	if x == nil {
		x = (*mpv_handle)(allocMpv_handleMemory(1))
	}
	return (*C.mpv_handle)(unsafe.Pointer(x))
}

// Ref returns a reference to C object as it is.
func (x *mpv_node) Ref() *C.mpv_node {
	if x == nil {
		return nil
	}
	return (*C.mpv_node)(unsafe.Pointer(x))
}

// Free cleanups the referenced memory using C free.
func (x *mpv_node) Free() {
	if x != nil {
		C.free(unsafe.Pointer(x))
	}
}

// Newmpv_nodeRef converts the C object reference into a raw struct reference without wrapping.
func mpv_node_ref(ref unsafe.Pointer) *mpv_node {
	return (*mpv_node)(ref)
}

// Newmpv_node allocates a new C object of this type and converts the reference into
// a raw struct reference without wrapping.
func mpv_node_new() *mpv_node {
	return (*mpv_node)(allocMpv_nodeMemory(1))
}

// allocMpv_nodeMemory allocates memory for type C.mpv_node in C.
// The caller is responsible for freeing the this memory via C.free.
func allocMpv_nodeMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfMpv_nodeValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfMpv_nodeValue = unsafe.Sizeof([1]C.mpv_node{})

// PassRef returns a reference to C object as it is or allocates a new C object of this type.
func (x *mpv_node) PassRef() *C.mpv_node {
	if x == nil {
		x = (*mpv_node)(allocMpv_nodeMemory(1))
	}
	return (*C.mpv_node)(unsafe.Pointer(x))
}

// Ref returns a reference to C object as it is.
func (x *mpv_node_list) Ref() *C.mpv_node_list {
	if x == nil {
		return nil
	}
	return (*C.mpv_node_list)(unsafe.Pointer(x))
}

// Free cleanups the referenced memory using C free.
func (x *mpv_node_list) Free() {
	if x != nil {
		C.free(unsafe.Pointer(x))
	}
}

// Newmpv_node_listRef converts the C object reference into a raw struct reference without wrapping.
func mpv_node_list_ref(ref unsafe.Pointer) *mpv_node_list {
	return (*mpv_node_list)(ref)
}

// Newmpv_node_list allocates a new C object of this type and converts the reference into
// a raw struct reference without wrapping.
func mpv_node_list_new() *mpv_node_list {
	return (*mpv_node_list)(allocMpv_node_listMemory(1))
}

// allocMpv_node_listMemory allocates memory for type C.mpv_node_list in C.
// The caller is responsible for freeing the this memory via C.free.
func allocMpv_node_listMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfMpv_node_listValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfMpv_node_listValue = unsafe.Sizeof([1]C.mpv_node_list{})

// PassRef returns a reference to C object as it is or allocates a new C object of this type.
func (x *mpv_node_list) PassRef() *C.mpv_node_list {
	if x == nil {
		x = (*mpv_node_list)(allocMpv_node_listMemory(1))
	}
	return (*C.mpv_node_list)(unsafe.Pointer(x))
}

// Ref returns a reference to C object as it is.
func (x *mpv_byte_array) Ref() *C.mpv_byte_array {
	if x == nil {
		return nil
	}
	return (*C.mpv_byte_array)(unsafe.Pointer(x))
}

// Free cleanups the referenced memory using C free.
func (x *mpv_byte_array) Free() {
	if x != nil {
		C.free(unsafe.Pointer(x))
	}
}

// Newmpv_byte_arrayRef converts the C object reference into a raw struct reference without wrapping.
func mpv_byte_array_ref(ref unsafe.Pointer) *mpv_byte_array {
	return (*mpv_byte_array)(ref)
}

// Newmpv_byte_array allocates a new C object of this type and converts the reference into
// a raw struct reference without wrapping.
func mpv_byte_array_new() *mpv_byte_array {
	return (*mpv_byte_array)(allocMpv_byte_arrayMemory(1))
}

// allocMpv_byte_arrayMemory allocates memory for type C.mpv_byte_array in C.
// The caller is responsible for freeing the this memory via C.free.
func allocMpv_byte_arrayMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfMpv_byte_arrayValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfMpv_byte_arrayValue = unsafe.Sizeof([1]C.mpv_byte_array{})

// PassRef returns a reference to C object as it is or allocates a new C object of this type.
func (x *mpv_byte_array) PassRef() *C.mpv_byte_array {
	if x == nil {
		x = (*mpv_byte_array)(allocMpv_byte_arrayMemory(1))
	}
	return (*C.mpv_byte_array)(unsafe.Pointer(x))
}

// Ref returns a reference to C object as it is.
func (x *mpv_event_property) Ref() *C.mpv_event_property {
	if x == nil {
		return nil
	}
	return (*C.mpv_event_property)(unsafe.Pointer(x))
}

// Free cleanups the referenced memory using C free.
func (x *mpv_event_property) Free() {
	if x != nil {
		C.free(unsafe.Pointer(x))
	}
}

// Newmpv_event_propertyRef converts the C object reference into a raw struct reference without wrapping.
func mpv_event_property_ref(ref unsafe.Pointer) *mpv_event_property {
	return (*mpv_event_property)(ref)
}

// Newmpv_event_property allocates a new C object of this type and converts the reference into
// a raw struct reference without wrapping.
func mpv_event_property_new() *mpv_event_property {
	return (*mpv_event_property)(allocMpv_event_propertyMemory(1))
}

// allocMpv_event_propertyMemory allocates memory for type C.mpv_event_property in C.
// The caller is responsible for freeing the this memory via C.free.
func allocMpv_event_propertyMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfMpv_event_propertyValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfMpv_event_propertyValue = unsafe.Sizeof([1]C.mpv_event_property{})

// PassRef returns a reference to C object as it is or allocates a new C object of this type.
func (x *mpv_event_property) PassRef() *C.mpv_event_property {
	if x == nil {
		x = (*mpv_event_property)(allocMpv_event_propertyMemory(1))
	}
	return (*C.mpv_event_property)(unsafe.Pointer(x))
}

// Ref returns a reference to C object as it is.
func (x *mpv_event_log_message) Ref() *C.mpv_event_log_message {
	if x == nil {
		return nil
	}
	return (*C.mpv_event_log_message)(unsafe.Pointer(x))
}

// Free cleanups the referenced memory using C free.
func (x *mpv_event_log_message) Free() {
	if x != nil {
		C.free(unsafe.Pointer(x))
	}
}

// Newmpv_event_log_messageRef converts the C object reference into a raw struct reference without wrapping.
func mpv_event_log_message_ref(ref unsafe.Pointer) *mpv_event_log_message {
	return (*mpv_event_log_message)(ref)
}

// Newmpv_event_log_message allocates a new C object of this type and converts the reference into
// a raw struct reference without wrapping.
func mpv_event_log_message_new() *mpv_event_log_message {
	return (*mpv_event_log_message)(allocMpv_event_log_messageMemory(1))
}

// allocMpv_event_log_messageMemory allocates memory for type C.mpv_event_log_message in C.
// The caller is responsible for freeing the this memory via C.free.
func allocMpv_event_log_messageMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfMpv_event_log_messageValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfMpv_event_log_messageValue = unsafe.Sizeof([1]C.mpv_event_log_message{})

// PassRef returns a reference to C object as it is or allocates a new C object of this type.
func (x *mpv_event_log_message) PassRef() *C.mpv_event_log_message {
	if x == nil {
		x = (*mpv_event_log_message)(allocMpv_event_log_messageMemory(1))
	}
	return (*C.mpv_event_log_message)(unsafe.Pointer(x))
}

// Ref returns a reference to C object as it is.
func (x *mpv_event_start_file) Ref() *C.mpv_event_start_file {
	if x == nil {
		return nil
	}
	return (*C.mpv_event_start_file)(unsafe.Pointer(x))
}

// Free cleanups the referenced memory using C free.
func (x *mpv_event_start_file) Free() {
	if x != nil {
		C.free(unsafe.Pointer(x))
	}
}

// Newmpv_event_start_fileRef converts the C object reference into a raw struct reference without wrapping.
func mpv_event_start_file_ref(ref unsafe.Pointer) *mpv_event_start_file {
	return (*mpv_event_start_file)(ref)
}

// Newmpv_event_start_file allocates a new C object of this type and converts the reference into
// a raw struct reference without wrapping.
func mpv_event_start_file_new() *mpv_event_start_file {
	return (*mpv_event_start_file)(allocMpv_event_start_fileMemory(1))
}

// allocMpv_event_start_fileMemory allocates memory for type C.mpv_event_start_file in C.
// The caller is responsible for freeing the this memory via C.free.
func allocMpv_event_start_fileMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfMpv_event_start_fileValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfMpv_event_start_fileValue = unsafe.Sizeof([1]C.mpv_event_start_file{})

// PassRef returns a reference to C object as it is or allocates a new C object of this type.
func (x *mpv_event_start_file) PassRef() *C.mpv_event_start_file {
	if x == nil {
		x = (*mpv_event_start_file)(allocMpv_event_start_fileMemory(1))
	}
	return (*C.mpv_event_start_file)(unsafe.Pointer(x))
}

// Ref returns a reference to C object as it is.
func (x *mpv_event_end_file) Ref() *C.mpv_event_end_file {
	if x == nil {
		return nil
	}
	return (*C.mpv_event_end_file)(unsafe.Pointer(x))
}

// Free cleanups the referenced memory using C free.
func (x *mpv_event_end_file) Free() {
	if x != nil {
		C.free(unsafe.Pointer(x))
	}
}

// Newmpv_event_end_fileRef converts the C object reference into a raw struct reference without wrapping.
func mpv_event_end_file_ref(ref unsafe.Pointer) *mpv_event_end_file {
	return (*mpv_event_end_file)(ref)
}

// Newmpv_event_end_file allocates a new C object of this type and converts the reference into
// a raw struct reference without wrapping.
func mpv_event_end_file_new() *mpv_event_end_file {
	return (*mpv_event_end_file)(allocMpv_event_end_fileMemory(1))
}

// allocMpv_event_end_fileMemory allocates memory for type C.mpv_event_end_file in C.
// The caller is responsible for freeing the this memory via C.free.
func allocMpv_event_end_fileMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfMpv_event_end_fileValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfMpv_event_end_fileValue = unsafe.Sizeof([1]C.mpv_event_end_file{})

// PassRef returns a reference to C object as it is or allocates a new C object of this type.
func (x *mpv_event_end_file) PassRef() *C.mpv_event_end_file {
	if x == nil {
		x = (*mpv_event_end_file)(allocMpv_event_end_fileMemory(1))
	}
	return (*C.mpv_event_end_file)(unsafe.Pointer(x))
}

// Ref returns a reference to C object as it is.
func (x *mpv_event_script_input_dispatch) Ref() *C.mpv_event_script_input_dispatch {
	if x == nil {
		return nil
	}
	return (*C.mpv_event_script_input_dispatch)(unsafe.Pointer(x))
}

// Free cleanups the referenced memory using C free.
func (x *mpv_event_script_input_dispatch) Free() {
	if x != nil {
		C.free(unsafe.Pointer(x))
	}
}

// Newmpv_event_script_input_dispatchRef converts the C object reference into a raw struct reference without wrapping.
func mpv_event_script_input_dispatch_ref(ref unsafe.Pointer) *mpv_event_script_input_dispatch {
	return (*mpv_event_script_input_dispatch)(ref)
}

// Newmpv_event_script_input_dispatch allocates a new C object of this type and converts the reference into
// a raw struct reference without wrapping.
func mpv_event_script_input_dispatch_new() *mpv_event_script_input_dispatch {
	return (*mpv_event_script_input_dispatch)(allocMpv_event_script_input_dispatchMemory(1))
}

// allocMpv_event_script_input_dispatchMemory allocates memory for type C.mpv_event_script_input_dispatch in C.
// The caller is responsible for freeing the this memory via C.free.
func allocMpv_event_script_input_dispatchMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfMpv_event_script_input_dispatchValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfMpv_event_script_input_dispatchValue = unsafe.Sizeof([1]C.mpv_event_script_input_dispatch{})

// PassRef returns a reference to C object as it is or allocates a new C object of this type.
func (x *mpv_event_script_input_dispatch) PassRef() *C.mpv_event_script_input_dispatch {
	if x == nil {
		x = (*mpv_event_script_input_dispatch)(allocMpv_event_script_input_dispatchMemory(1))
	}
	return (*C.mpv_event_script_input_dispatch)(unsafe.Pointer(x))
}

// Ref returns a reference to C object as it is.
func (x *mpv_event_client_message) Ref() *C.mpv_event_client_message {
	if x == nil {
		return nil
	}
	return (*C.mpv_event_client_message)(unsafe.Pointer(x))
}

// Free cleanups the referenced memory using C free.
func (x *mpv_event_client_message) Free() {
	if x != nil {
		C.free(unsafe.Pointer(x))
	}
}

// Newmpv_event_client_messageRef converts the C object reference into a raw struct reference without wrapping.
func mpv_event_client_message_ref(ref unsafe.Pointer) *mpv_event_client_message {
	return (*mpv_event_client_message)(ref)
}

// Newmpv_event_client_message allocates a new C object of this type and converts the reference into
// a raw struct reference without wrapping.
func mpv_event_client_message_new() *mpv_event_client_message {
	return (*mpv_event_client_message)(allocMpv_event_client_messageMemory(1))
}

// allocMpv_event_client_messageMemory allocates memory for type C.mpv_event_client_message in C.
// The caller is responsible for freeing the this memory via C.free.
func allocMpv_event_client_messageMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfMpv_event_client_messageValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfMpv_event_client_messageValue = unsafe.Sizeof([1]C.mpv_event_client_message{})

// PassRef returns a reference to C object as it is or allocates a new C object of this type.
func (x *mpv_event_client_message) PassRef() *C.mpv_event_client_message {
	if x == nil {
		x = (*mpv_event_client_message)(allocMpv_event_client_messageMemory(1))
	}
	return (*C.mpv_event_client_message)(unsafe.Pointer(x))
}

// Ref returns a reference to C object as it is.
func (x *mpv_event_hook) Ref() *C.mpv_event_hook {
	if x == nil {
		return nil
	}
	return (*C.mpv_event_hook)(unsafe.Pointer(x))
}

// Free cleanups the referenced memory using C free.
func (x *mpv_event_hook) Free() {
	if x != nil {
		C.free(unsafe.Pointer(x))
	}
}

// Newmpv_event_hookRef converts the C object reference into a raw struct reference without wrapping.
func mpv_event_hook_ref(ref unsafe.Pointer) *mpv_event_hook {
	return (*mpv_event_hook)(ref)
}

// Newmpv_event_hook allocates a new C object of this type and converts the reference into
// a raw struct reference without wrapping.
func mpv_event_hook_new() *mpv_event_hook {
	return (*mpv_event_hook)(allocMpv_event_hookMemory(1))
}

// allocMpv_event_hookMemory allocates memory for type C.mpv_event_hook in C.
// The caller is responsible for freeing the this memory via C.free.
func allocMpv_event_hookMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfMpv_event_hookValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfMpv_event_hookValue = unsafe.Sizeof([1]C.mpv_event_hook{})

// PassRef returns a reference to C object as it is or allocates a new C object of this type.
func (x *mpv_event_hook) PassRef() *C.mpv_event_hook {
	if x == nil {
		x = (*mpv_event_hook)(allocMpv_event_hookMemory(1))
	}
	return (*C.mpv_event_hook)(unsafe.Pointer(x))
}

// Ref returns a reference to C object as it is.
func (x *mpv_event_command) Ref() *C.mpv_event_command {
	if x == nil {
		return nil
	}
	return (*C.mpv_event_command)(unsafe.Pointer(x))
}

// Free cleanups the referenced memory using C free.
func (x *mpv_event_command) Free() {
	if x != nil {
		C.free(unsafe.Pointer(x))
	}
}

// Newmpv_event_commandRef converts the C object reference into a raw struct reference without wrapping.
func mpv_event_command_ref(ref unsafe.Pointer) *mpv_event_command {
	return (*mpv_event_command)(ref)
}

// Newmpv_event_command allocates a new C object of this type and converts the reference into
// a raw struct reference without wrapping.
func mpv_event_command_new() *mpv_event_command {
	return (*mpv_event_command)(allocMpv_event_commandMemory(1))
}

// allocMpv_event_commandMemory allocates memory for type C.mpv_event_command in C.
// The caller is responsible for freeing the this memory via C.free.
func allocMpv_event_commandMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfMpv_event_commandValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfMpv_event_commandValue = unsafe.Sizeof([1]C.mpv_event_command{})

// PassRef returns a reference to C object as it is or allocates a new C object of this type.
func (x *mpv_event_command) PassRef() *C.mpv_event_command {
	if x == nil {
		x = (*mpv_event_command)(allocMpv_event_commandMemory(1))
	}
	return (*C.mpv_event_command)(unsafe.Pointer(x))
}

// Ref returns a reference to C object as it is.
func (x *mpv_event) Ref() *C.mpv_event {
	if x == nil {
		return nil
	}
	return (*C.mpv_event)(unsafe.Pointer(x))
}

// Free cleanups the referenced memory using C free.
func (x *mpv_event) Free() {
	if x != nil {
		C.free(unsafe.Pointer(x))
	}
}

// Newmpv_eventRef converts the C object reference into a raw struct reference without wrapping.
func mpv_event_ref(ref unsafe.Pointer) *mpv_event {
	return (*mpv_event)(ref)
}

// Newmpv_event allocates a new C object of this type and converts the reference into
// a raw struct reference without wrapping.
func mpv_event_new() *mpv_event {
	return (*mpv_event)(allocMpv_eventMemory(1))
}

// allocMpv_eventMemory allocates memory for type C.mpv_event in C.
// The caller is responsible for freeing the this memory via C.free.
func allocMpv_eventMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfMpv_eventValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfMpv_eventValue = unsafe.Sizeof([1]C.mpv_event{})

// PassRef returns a reference to C object as it is or allocates a new C object of this type.
func (x *mpv_event) PassRef() *C.mpv_event {
	if x == nil {
		x = (*mpv_event)(allocMpv_eventMemory(1))
	}
	return (*C.mpv_event)(unsafe.Pointer(x))
}

// packPCharString creates a Go string backed by *C.char and avoids copying.
func packPCharString(p *C.char) (raw string) {
	if p != nil && *p != 0 {
		h := (*stringHeader)(unsafe.Pointer(&raw))
		h.Data = unsafe.Pointer(p)
		for *p != 0 {
			p = (*C.char)(unsafe.Pointer(uintptr(unsafe.Pointer(p)) + 1)) // p++
		}
		h.Len = int(uintptr(unsafe.Pointer(p)) - uintptr(h.Data))
	}
	return
}

type stringHeader struct {
	Data unsafe.Pointer
	Len  int
}

// rawString reperesents a string backed by data on the C side.
type rawString string

// Copy returns a Go-managed copy of raw string.
func (raw rawString) Copy() string {
	if len(raw) == 0 {
		return ""
	}
	h := (*stringHeader)(unsafe.Pointer(&raw))
	return C.GoStringN((*C.char)(h.Data), C.int(h.Len))
}

// unpackPCharString copies the data from Go string as *C.char.
func unpackPCharString(str string) (*C.char, *cgoAllocMap) {
	allocs := new(cgoAllocMap)
	defer runtime.SetFinalizer(allocs, func(a *cgoAllocMap) {
		go a.Free()
	})

	mem0 := unsafe.Pointer(C.CString(str))
	allocs.Add(mem0)
	return (*C.char)(mem0), allocs
}

type sliceHeader struct {
	Data unsafe.Pointer
	Len  int
	Cap  int
}

// allocPCharMemory allocates memory for type *C.char in C.
// The caller is responsible for freeing the this memory via C.free.
func allocPCharMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfPCharValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfPCharValue = unsafe.Sizeof([1]*C.char{})

const sizeOfPtr = unsafe.Sizeof(&struct{}{})

// unpackArgSString transforms a sliced Go data structure into plain C format.
func unpackArgSString(x []string) (unpacked **C.char, allocs *cgoAllocMap) {
	if x == nil {
		return nil, nil
	}
	allocs = new(cgoAllocMap)
	defer runtime.SetFinalizer(allocs, func(a *cgoAllocMap) {
		go a.Free()
	})

	len0 := len(x)
	mem0 := allocPCharMemory(len0)
	allocs.Add(mem0)
	h0 := &sliceHeader{
		Data: mem0,
		Cap:  len0,
		Len:  len0,
	}
	v0 := *(*[]*C.char)(unsafe.Pointer(h0))
	for i0 := range x {
		v0[i0], _ = unpackPCharString(x[i0])
	}
	h := (*sliceHeader)(unsafe.Pointer(&v0))
	unpacked = (**C.char)(h.Data)
	return
}

// packSString reads sliced Go data structure out from plain C format.
func packSString(v []string, ptr0 **C.char) {
	const m = 0x7fffffff
	for i0 := range v {
		ptr1 := (*(*[m / sizeOfPtr]*C.char)(unsafe.Pointer(ptr0)))[i0]
		v[i0] = packPCharString(ptr1)
	}
}

// copyPMpv_nodeBytes copies the data from Go slice as *C.mpv_node.
func copyPMpv_nodeBytes(slice *sliceHeader) (*C.mpv_node, *cgoAllocMap) {
	allocs := new(cgoAllocMap)
	defer runtime.SetFinalizer(allocs, func(a *cgoAllocMap) {
		go a.Free()
	})

	mem0 := unsafe.Pointer(C.CBytes(*(*[]byte)(unsafe.Pointer(&sliceHeader{
		Data: slice.Data,
		Len:  int(sizeOfMpv_nodeValue) * slice.Len,
		Cap:  int(sizeOfMpv_nodeValue) * slice.Len,
	}))))
	allocs.Add(mem0)

	return (*C.mpv_node)(mem0), allocs
}
