// WARNING: This file has automatically been generated
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package internal

/*
#include "mpv.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

// handle as declared in mpv/client.h:259
type handle = C.mpv_handle

// node as declared in mpv/client.h:837
type node = C.mpv_node

// node_list as declared in mpv/client.h:869
type node_list = C.mpv_node_list

// byte_array as declared in mpv/client.h:884
type byte_array = C.mpv_byte_array

// event_property as declared in mpv/client.h:1538
type event_property = C.mpv_event_property

// event_log_message as declared in mpv/client.h:1582
type event_log_message = C.mpv_event_log_message

// event_start_file as declared in mpv/client.h:1626
type event_start_file = C.mpv_event_start_file

// event_end_file as declared in mpv/client.h:1671
type event_end_file = C.mpv_event_end_file

// event_script_input_dispatch as declared in mpv/client.h:1679
type event_script_input_dispatch = C.mpv_event_script_input_dispatch

// event_client_message as declared in mpv/client.h:1691
type event_client_message = C.mpv_event_client_message

// event_hook as declared in mpv/client.h:1702
type event_hook = C.mpv_event_hook

// event_command as declared in mpv/client.h:1713
type event_command = C.mpv_event_command

// event as declared in mpv/client.h:1760
type event = C.mpv_event
