#!/bin/bash -ev
pkg=internal
mkdir -p tmp/
c-for-go  -ccdefs -ccincl -nostamp -out tmp/ generate.yml
sed '
	/New([^( ]*)Ref/s//\1_ref/g
	/New([^( ]*)/s//\1_new/g
	/RawString/s//rawString/g
' -E -i "tmp/$pkg/cgo_helpers.go"
sed '
	/^\t(.*) [^ ]* = (.*)$/s//\t\1 = \2/g
' -E -i "tmp/$pkg/const.go"
sed '
	/^type ([^ ]*) ([^ ]*)$/s//type \1 = \2/g
' -E -i "tmp/$pkg/types.go"
for file in cgo_helpers.{go,h}; do
	mv "tmp/$pkg/$file" "$file"
done
for file in const.go internal.go types.go; do
	mv "tmp/$pkg/$file" "cgo_$file"
done
nm -D /usr/bin/mpv | awk '
	BEGIN {
		print "// Code generated by BOTS. DO NOT EDIT."
		print "#pragma once"
		print "#include \"client.h\""
		print "#include \"render.h\""
		print "#include \"opengl_cb.h\""
		print "#include \"stream_cb.h\""
	}
	/ T / {
		print "#pragma weak " $3
	}
' > mpv.h
cp /usr/include/mpv/* .
rm -rf tmp/
goimports -w -l .
gofumpt -w -l .
