// Code generated by BOTS. DO NOT EDIT.
#pragma once
#include "client.h"
#include "render.h"
#include "opengl_cb.h"
#include "stream_cb.h"
#pragma weak mpv_abort_async_command
#pragma weak mpv_client_api_version
#pragma weak mpv_client_id
#pragma weak mpv_client_name
#pragma weak mpv_command
#pragma weak mpv_command_async
#pragma weak mpv_command_node
#pragma weak mpv_command_node_async
#pragma weak mpv_command_ret
#pragma weak mpv_command_string
#pragma weak mpv_create
#pragma weak mpv_create_client
#pragma weak mpv_create_weak_client
#pragma weak mpv_destroy
#pragma weak mpv_detach_destroy
#pragma weak mpv_error_string
#pragma weak mpv_event_name
#pragma weak mpv_event_to_node
#pragma weak mpv_free
#pragma weak mpv_free_node_contents
#pragma weak mpv_get_property
#pragma weak mpv_get_property_async
#pragma weak mpv_get_property_osd_string
#pragma weak mpv_get_property_string
#pragma weak mpv_get_sub_api
#pragma weak mpv_get_time_us
#pragma weak mpv_get_wakeup_pipe
#pragma weak mpv_hook_add
#pragma weak mpv_hook_continue
#pragma weak mpv_initialize
#pragma weak mpv_load_config_file
#pragma weak mpv_observe_property
#pragma weak mpv_opengl_cb_draw
#pragma weak mpv_opengl_cb_init_gl
#pragma weak mpv_opengl_cb_render
#pragma weak mpv_opengl_cb_report_flip
#pragma weak mpv_opengl_cb_set_update_callback
#pragma weak mpv_opengl_cb_uninit_gl
#pragma weak mpv_render_context_create
#pragma weak mpv_render_context_free
#pragma weak mpv_render_context_get_info
#pragma weak mpv_render_context_render
#pragma weak mpv_render_context_report_swap
#pragma weak mpv_render_context_set_parameter
#pragma weak mpv_render_context_set_update_callback
#pragma weak mpv_render_context_update
#pragma weak mpv_request_event
#pragma weak mpv_request_log_messages
#pragma weak mpv_resume
#pragma weak mpv_set_option
#pragma weak mpv_set_option_string
#pragma weak mpv_set_property
#pragma weak mpv_set_property_async
#pragma weak mpv_set_property_string
#pragma weak mpv_set_wakeup_callback
#pragma weak mpv_stream_cb_add_ro
#pragma weak mpv_suspend
#pragma weak mpv_terminate_destroy
#pragma weak mpv_unobserve_property
#pragma weak mpv_wait_async_requests
#pragma weak mpv_wait_event
#pragma weak mpv_wakeup
